from enum import Enum


sync = b'\x9c\xae'

class messageId(Enum):
    SATELLITE_VISIBILITY_DATA=0x04
    EXTERNAL_EVENT_1_DATA=0x05
    EXTERNAL_EVENT_2_DATA=0x06
    REFERENCE_STATION_POSITION=0x09
    METEOROLOGICAL_AND_INCLINATION_DATA=0x10
    GPS_SUBSYSTEM_REFERENCE_DATA_STATUS=0x11
    MEASUREMENT_DATA_32BIT_INTEGER_OPTIMIZED=0x0c
    
    LB2_OUTPUT_MESSAGE_CONTR0L=0x82
    USER_TIME_CLOCK_PARAMETERS=0x84
    GPS_SUBSYSTEM_TIME_DATE_AND_INITIAL_POSITION=0x85
    SATELLITE_TRACKING_CONTROL=0x86
    SATELLITE_DATA=0x88
    NMEA_OUTPUT_MESSAGE_CONTROL=0x92
    SURVEY_SYSTEM_SPECIFIC_SUBMESSAGES=0xfa
    LB2_SUBMESSAGE_OUTPUT_CONTROL=0xfb

